image: ruby:3.3

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gem install bundler jekyll
    - bundle install --jobs 4 --retry 3
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main

pages:
  stage: deploy
  # this script can be as simple as a noop
  script:
    - echo "Publishing Pages…"
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - main
