title: Portfolio
description: >
  Full-stack web developer portfolio showcasing recent projects,
  programming languages, and other relevant skills and experiences.
baseurl: "/portfolio"

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/css/tailwind-input.css

# Build settings
plugins:
  - jekyll-feed
  - jekyll-polyglot

# Language settings
languages: ["en", "de", "es"]
default_lang: "en"
linkedin_url: "https://www.linkedin.com/in/verena-lechner"
github_url: "https://www.github.com/vr33ni" # personal account (primary)
github_org_url: "https://github.com/vr33ni-dev" # organisation (secondary)



# Exclude from localization
exclude_from_localization:
  - assets/
 
polyglot:
  default_lang_in_subfolder: false
parallel_localization: false