title: Portfolio
description: >
  Full-stack web developer portfolio showcasing recent projects,
  programming languages, and other relevant skills and experiences.
baseurl: "" # gitlab: "https://portfolio-4e3463.gitlab.io" / "" -  github: "/portfolio" # Adjust if your site is hosted in a subdirectory

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot

# Language settings
languages: ["en", "de", "es"]
default_lang: "en"

# Exclude from localization
exclude_from_localization:
  - assets/
 
polyglot:
  default_lang_in_subfolder: false
parallel_localization: false